server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: https://localhost:8761/eureka
  instance:
    hostname: localhost
spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            authorization-uri: http://localhost:9090/realms/api-realm/protocol/openid-connect/auth
            userinfo-uri: http://localhost:9090/realms/api-realm/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
            token-uri: http://localhost:9090/realms/api-realm/protocol/openid-connect/token
          registration:
            api-client:
              provider: keycloak
              client-id: api-client
              client-secret: HVWtAJutmwOsv8EK7rVkx9SvEQ3fX2qw
              authorization-grant-type: authorization_code
              redirect-uri: "{baseUrl}/login/oauth2/code/api-client"
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      discovery:
        locator:
          enabled: true
      routes:
        - id: ms-user
          uri: lb://ms-user
          predicates:
            - Path=/users/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: ms-bike
          uri: lb://ms-bike
          predicates:
            - Path=/bikes/**
        - id: ms-car
          uri: lb://ms-car
          predicates:
            - Path=/cars/**